spring:

#  H2 DATABASE
#  Url de acceso a BBDD -> http://localhost:8081/h2-console/

  h2.console.enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:coelsabd
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
   
server:
  port: 8081